### ISSUE TITLE
Add documentation about MogNotate drum mapper.

### ISSUE THREAD

**Issue by Meowchestra** [BardMusicPlayer/Website#4]
Need information for the following;

* Default percussion mappings notable automatically tries to convert for snare, bass, bongo, cymbal, and timpani drums when specified.
* Information about how to override notes that are not being default mapped to a specific drum type & note, as well as how to override the default mapping.

i.e.
```
    map_42_drum: Snare
    map_42_note: 20
```

**Comment by troy-f** [comment]
#13
